### ISSUE TITLE
Maintenance release for 8.0.x

### ISSUE THREAD

**Issue by zalavaari** [eclipse-ee4j/jakartaee-api#102] opened 2021-04-22 07:25 UTC
Please create a maintenance release for 8.0.x, which contains the fixes for the missing properties, which were fixed in PR #49

**Comment by smillidge** [comment] 2021-04-27 15:54
Duplicate of #97

**Comment by kwsutter** [comment] 2021-04-27 22:02
> Duplicate of #97

Right.  We only need one issue for creating the 8.0.x release.

**Closed** 2022-03-17 21:18 UTC
